from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

    from .models import Model
    from .query import Q


@runtime_checkable
class Executor(Protocol):
    """
    Runs the SQL generated by a `QuerySet`. `Database` is the standard implementation, but any object with these
    methods can be passed to `QuerySet` or `Model.objects_in` (e.g. a stub in unit tests).

    Generated queries rely on the executor to:

    - substitute the `$db` placeholder with its database name (used by `delete` / `update`);
    - resolve unqualified table names against that same database (used by `SELECT` queries).
    """

    def select(
        self, query: str, model_class: type[Model] | None = None, settings: Mapping[str, object] | None = None
    ) -> Iterable[Model]:
        """
        Runs a query and returns its rows as instances of `model_class`, or of an ad-hoc model when it is `None`.
        """
        ...

    def raw(self, query: str, settings: Mapping[str, object] | None = None, stream: bool = False) -> str:
        """
        Runs a query and returns its output as text.
        """
        ...

    def count(self, model_class: type[Model], conditions: str | Q | None = None) -> int:
        """
        Returns the number of rows in the model's table matching the optional `WHERE` conditions.
        """
        ...


__all__ = ["Executor"]
