"""
Query parameters: values sent separately from the SQL text and referenced as `{name:Type}` placeholders.

ClickHouse parses parameter values using the same escaped text format as TabSeparated data, so a value is
encoded exactly like a cell of a TSV insert (`Field.to_db_string(value, quote=False)`).
"""

from __future__ import annotations

import dataclasses
import enum
from calendar import timegm
from contextlib import contextmanager
from contextvars import ContextVar
from datetime import date, datetime
from decimal import Decimal
from ipaddress import IPv4Address, IPv6Address
from typing import TYPE_CHECKING, Any
from uuid import UUID

import pytz

from .utils import escape

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping

    from .fields import Field


@dataclasses.dataclass(frozen=True)
class EncodedParam:
    """
    A query parameter value which is already encoded in ClickHouse's escaped text format, and is sent as is.
    Use `EncodedParam.for_field` to encode a value exactly like a model field does.
    """

    text: str

    @classmethod
    def for_field(cls, field: Field, value: Any) -> EncodedParam:
        """Encodes `value` using the conversion rules of `field`."""
        return cls(field._param_text(field.to_python(value, pytz.utc)))


class QueryParams:
    """Collects the parameters bound while compiling a query."""

    prefix = "_orm_p"

    def __init__(self):
        self.values: dict[str, EncodedParam] = {}

    def bind(self, text: str, db_type: str) -> str:
        """Registers an encoded value and returns the `{name:Type}` placeholder referencing it."""
        name = f"{self.prefix}{len(self.values)}"
        self.values[name] = EncodedParam(text)
        return "{%s:%s}" % (name, db_type)

    def bind_field_value(self, field: Field, value: Any) -> str:
        """
        Binds a value that was already converted by `field.to_python`. NULL is returned inline as `\\N`,
        so that operators can still turn comparisons with it into `IS NULL`.
        """
        text = field._param_text(value)
        if text == "\\N":
            return text
        return self.bind(text, field._param_type())


_active_params: ContextVar[QueryParams | None] = ContextVar("clickhouse_orm_query_params", default=None)


def active_params() -> QueryParams | None:
    """Returns the parameters being collected by the enclosing `collect_params()` block, if any."""
    return _active_params.get()


@contextmanager
def collect_params() -> Iterator[QueryParams]:
    """
    While active, SQL generated by querysets, operators and functions binds values as parameters instead of
    inlining them. Nested blocks (e.g. compiling a subquery) share the outermost collection.
    """
    current = _active_params.get()
    if current is not None:
        yield current
        return
    params = QueryParams()
    token = _active_params.set(params)
    try:
        yield params
    finally:
        _active_params.reset(token)


def format_param(value: Any) -> str:
    """
    Encodes a Python value as the text of a query parameter. Supports None, strings, booleans, numbers,
    dates, datetimes (naive ones are wall-clock times in the placeholder's timezone), UUIDs, IP addresses, enums
    (by name), lists (arrays), tuples and dicts (maps), as well as `EncodedParam` instances which are passed
    through unchanged.
    """
    if isinstance(value, EncodedParam):
        return value.text
    if value is None:
        return "\\N"
    if isinstance(value, str):
        return escape(value, quote=False)
    if isinstance(value, enum.Enum):
        return escape(value.name, quote=False)
    if isinstance(value, (list, tuple, dict)):
        return _format_element(value)
    return _format_scalar(value)


def encode_params(params: Mapping[str, Any] | None) -> dict[str, str] | None:
    """Encodes a mapping of parameter names to values with `format_param`."""
    if not params:
        return None
    return {name: format_param(value) for name, value in params.items()}


def _format_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float, Decimal)):
        return str(value)
    if isinstance(value, datetime):
        if value.tzinfo is None or value.utcoffset() is None:
            # Naive datetimes are wall-clock times, which ClickHouse interprets in the placeholder type's timezone
            return value.isoformat(" ", "microseconds" if value.microsecond else "seconds")
        timestamp = timegm(value.utctimetuple())
        return f"{timestamp}.{value.microsecond:06d}" if value.microsecond else str(timestamp)
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, (UUID, IPv4Address, IPv6Address)):
        return str(value)
    raise TypeError(f"Unsupported query parameter value: {value!r} (use EncodedParam to pass pre-encoded text)")


def _format_element(value: Any) -> str:
    # Values nested inside arrays, tuples and maps use the quoted literal syntax
    if value is None:
        return "NULL"
    if isinstance(value, list):
        return "[" + ",".join(_format_element(v) for v in value) + "]"
    if isinstance(value, tuple):
        return "(" + ",".join(_format_element(v) for v in value) + ")"
    if isinstance(value, dict):
        return "{" + ",".join(f"{_format_element(k)}:{_format_element(v)}" for k, v in value.items()) + "}"
    if isinstance(value, str):
        return escape(value)
    if isinstance(value, enum.Enum):
        return escape(value.name)
    if isinstance(value, (bool, int, float, Decimal)):
        return _format_scalar(value)
    return escape(_format_scalar(value))


__all__ = ["EncodedParam", "QueryParams", "active_params", "collect_params", "encode_params", "format_param"]
