[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "clickhouse_orm"
version = "2.2.2"
readme = "README.md"
description = "A simple ORM for working with the Clickhouse database. Maintainance fork of infi.clickhouse_orm."
# authors = ["olliemath <oliver.margetts@gmail.com>"]
# license = "BSD"
# homepage = "https://github.com/SuadeLabs/clickhouse_orm"
# repository = "https://github.com/SuadeLabs/clickhouse_orm"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Database",
]
# requires_python = "sqlalchemy-utils>=0.41.1"
dependencies = [
    "requests",
    "pytz",
    "iso8601",
]

[project.optional-dependencies]
dev = [
  "freezegun==1.5.5",
  "pytest==9.0.2",
  "ruff==0.14.14",
]

[tool.ruff]
line-length = 120
target-version = "py310"
# File Selection
force-exclude = true  # don't check excluded files even if passed directly
extend-exclude = ["./venv"]

[tool.ruff.lint]
# Rule Selection
# to read about ruff rules check this: https://beta.ruff.rs/docs/rules/
select = [
  "E",
  "W",       # pycodestyle: E, W
  "F",       # pyflakes: F
  "B",       # flake8-bugbear: B
  "ISC",     # flake8-implicit-str-concat: ISC
  "N",       # pep8-naming: N
  "PYI",     # flake8-pyi: PYI
  "RUF013",  # ruff: RUF (Specifically implicit-optional)
  "RUF022",  # unsorted-dunder-all: https://docs.astral.sh/ruff/rules/unsorted-dunder-all/
  "RUF023",  # unsorted-dunder-slots: https://docs.astral.sh/ruff/rules/unsorted-dunder-slots/
  "RUF101",  # redirected-noqa: https://docs.astral.sh/ruff/rules/redirected-noqa/
  "T10",     # flake8-debugger
  "TC",      # flake8-type-checking
  "UP",      # pyupgrade: U
]

ignore = [
  "B904",   # raising without from clause
  "B905",   # zip without strict parameter
  "E501",   # line-too-long
  "F403",   # from module import *
  "F405",   # name defined from star imports
  "N802",   # function names often mirror clickhouse function names
  "N806",   # dynamically created classes
  "N999",   # migration module names: 1234.py
  "UP031",  # percent formatting
]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
relative-imports-order = "closest-to-furthest"
combine-as-imports = true
split-on-trailing-comma = false
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]
