# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Lint on smallest and largest active versions
        python-version: ["3.10", "3.11", "3.14"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
    - name: Lint with ruff
      run: |
        ruff check .
    - name: Check formatting with ruff
      run: |
        ruff format --check .

  test:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:25.8
        ports:
          - 8123:8123
        env:
          CLICKHOUSE_SKIP_USER_SETUP: "1"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.14", "pypy3.10"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
    - name: Test with pytest
      run: |
        pytest .

  test_compat_21_3:
    # Tests compatibility with an older LTS release of clickhouse
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: yandex/clickhouse-server:21.3
        ports:
          - 8123:8123
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
    - name: Test with pytest
      run: |
        pytest .

  test_compat_20_8:
    # Tests compatibility with an older LTS release of clickhouse
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: yandex/clickhouse-server:20.8
        ports:
          - 8123:8123
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
    - name: Test with pytest
      run: |
        pytest .
